### ISSUE TITLE
Command not found: ts-node-dev

### ISSUE THREAD

**Issue by Magofoco** [wclr/ts-node-dev#189]
Hello!

I am moving from `nodemon` to `ts-node-dev` but I am not able to run my `index.ts` file using` ts-node-dev`.

I did the following:

1) `yarn add ts-node-dev --dev`
2) In my `package.json` I have:

```
"devDependencies": {
   ...
   "nodemon": "^1.19.2",
   "ts-node": "8.3.0",
   "ts-node-dev": "^1.0.0-pre.56",
   "typescript": "3.6.3"
}
```
If I run `ts-node-dev` or `ts-node-dev src/index.ts` I get the error: **command not found: ts-node-dev**

**Comment by whitecolor** [comment]
`yarn ts-node-dev src/index.ts`?

**Comment by Magofoco** [comment]
> yarn ts-node-dev src/index.ts

I get the same issue:

![Screenshot 2020-08-04 at 10 52 39](https://user-images.githubusercontent.com/34609892/89274009-9ee0b900-d640-11ea-8766-05bddfc8c640.png)

**Comment by whitecolor** [comment]
`ts-node` works? check `node_modules/bin/ts-node-dev`.

**Comment by Magofoco** [comment]
> `ts-node` works? check `node_modules/bin/ts-node-dev`.

Yes, `ts-node` does work.
Yes, I have `node_modules/bin/ts-node-dev
![Screenshot 2020-08-04 at 18 47 32](https://user-images.githubusercontent.com/34609892/89321328-218a6800-d683-11ea-8a20-13e759e6416c.png)

![Screenshot 2020-08-04 at 18 46 24](https://user-images.githubusercontent.com/34609892/89321136-ce181a00-d682-11ea-8e2b-bbd7fb668b72.png)

**Comment by rjerue** [comment]
What version of yarn are you running? Does `npx ts-node-dev src/index.ts` work? Isn't it supposed to also be in `.bin`?

As in: `node_modules/.bin/ts-node-dev`

**Comment by xiaomuzizier** [comment]
I get the same issue:

**Comment by wclr** [comment]
@xiaomuzizier you should install globally to run this way, otherwise you should use `npx/yarn` as command prefix.

**Comment by xiaomuzizier** [comment]
> @xiaomuzizier you should install globally to run this way, otherwise you should use `npx/yarn` as command prefix.

According to your suggestion, I can use it normally. Thank you very much！！！
@wclr

**Comment by omar-dulaimi** [comment]
I have the same issue. It was working fine before. It doesn't work with npx.

I tried to install it as a dep, as a dev dep, globally, with npx. Nothing worked!

**Comment by omar-dulaimi** [comment]
It was caused by a colon in the name of a parent folder like this:

`./usr/examples 3:58/typegraphql-example`

removing the colon fixed the issue.
