### ISSUE TITLE
--watch is not working

### ISSUE THREAD

**Issue by thany** [wclr/ts-node-dev#233]
## Issue description

I'm trying to add an arbitrary file to being watched for changes, which isn't working. The change isn't being picked up and the app is not getting auto-restarted.

Now, the docs say I have to use a "chokidar" pattern, and the link to it just goes to the chokidar project page, which leaves me none the wiser. But, I'm assuming that a straight filename (no spaces or any forbidden/weird characters) oughta work.

## Context

*OS version (is it docker or host?), ts-node-dev version*
Windows 10, ts-node-dev 1.0.0

*Did you try to run with [ts-node](https://github.com/TypeStrong/ts-node)*?
Not relevant.

*Did you try to run with `--files` option enabled?*
Yes, and it doesn't do anything (it's not in the docs, so I didn't expect anything)

*Did you try to run with `--debug` option enabled?*
Yup, but I'm not getting any more information than without it:
```
[INFO] 00:44:33 ts-node-dev ver. 1.0.0 (using ts-node ver. 9.0.0, typescript ver. 4.1.1-rc)
```
That's it.

*Do you have a repro example (git repo) with simple steps to reproduce your problem?*
Not yet, but since the problem is not related to any typescript code, the command can be tested against basically any codebase:
```
ts-node-dev --respawn --transpile-only ./src/app.ts --watch gallery.json --debug
```
Just make sure that `gallery.json` exists, and then just give it an edit while the app runs. It won't restart.

**Comment by pauliusg** [comment]
@thany, I think it is because of the order of params. I have moved watch before the entry script and it started to work:
`ts-node-dev --respawn --rs --watch ./**/*.yaml index.ts`

**Comment by thany** [comment]
Really? I'll try that out shortly. Thanks.

That would be a super weird side-effect. Order of arguments shoudn't matter (or alternatively, why should they?)

**Comment by rubengmurray** [comment]
Yep, just found this myself:

- `ts-node-dev --respawn --watch src ./src/index.ts` - hot reloads all files inside of `src`
- `ts-node-dev --respawn ./src/index.ts --watch src` - no hot reload for files inside of `src`

**Comment by thany** [comment]
Nah, don't close. I would rather see this fixed 😟

Or documented, but fixing it is nicer.

**Comment by rubengmurray** [comment]
Yeah I hear you, but I do think it is documented here in terms of arg order: https://github.com/wclr/ts-node-dev#usage so I suggested to close as imo it is working as documented. 

Handling args in a less opinionated order would maybe be a bigger issue to resolve?

**Comment by thany** [comment]
It doesn't say specifically that order is important (because in most tools, it isn't), but at least it's implied. Kind of.
