### ISSUE TITLE
Install failure on v1.1.1

### ISSUE THREAD

**Issue by prakharsingh** [wclr/ts-node-dev#235]
npm install fails with below error

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path [__dirname]/node_modules/ts-node-dev/lib\bin.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '[__dirname]/node_modules/ts-node-dev/lib\bin.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     [some_path]/.npm/_logs/[file_name]-debug.log

**Comment by prakharsingh** [comment]
duplicate of #224

**Comment by whitecolor** [comment]
I don't know what this issue is related to.

**Comment by tiankongoyll** [comment]
I had the same problem and switched to the pre.65 installation

**Comment by mantysalo** [comment]
For some reason the bin path is not the same in these as it's in the repository: 

https://registry.npmjs.org/ts-node-dev/1.1.1
https://registry.yarnpkg.com/ts-node-dev/1.1.1

https://github.com/wclr/ts-node-dev/blob/f6eb46f30f068bd3fe97cad3fb8a530d0eaaa495/package.json#L18

**Comment by wclr** [comment]
Should be fixed.

**Comment by mantysalo** [comment]
Seems to still be the case:

https://registry.npmjs.org/ts-node-dev/1.1.3
https://registry.yarnpkg.com/ts-node-dev/1.1.3

for some reason unpkg has the correct path for 1.1.1 and 1.1.3 🤷‍♂️ 

https://unpkg.com/ts-node-dev@1.1.1/package.json
https://unpkg.com/ts-node-dev@1.1.3/package.json

What makes this even more weird is that the installation works just fine with npm version 6, but with version 5 it fails with the error described in the original post.

**Comment by wclr** [comment]
Closing. It was because np was using lame yarn for publishing.
