### ISSUE TITLE
Cannot redeclare block-scoped variable

### ISSUE THREAD

**Issue by mlbonniec** [wclr/ts-node-dev#247]
## Issue description
Hi, when I want to use `ts-node-dev`, I encounter an issue. Firstly, I have to use `tsconfig-path` to make TS understand my custom paths. The problem is when `tsnd` is compiling, I get the error `Cannot redeclare block-scoped variable 'passport_1'.`.
Where does it come from? And how to fix it?

My start script ⬇️
```
tsnd --clear --debug --files -r ts-node/register -r tsconfig-paths/register ./src/app.ts
```
## Context

I'm running:
* macOS Big Sur 11.2
* Typescript 4.1.5
* ts-node-dev 1.1.1
* tsconfig-paths 3.9.0

*Did you try to run with [ts-node](https://github.com/TypeStrong/ts-node)*?
Yes, same error

*Did you try to run with `--files` option enabled?*
Yes, I need this option to use my custom types.

I tried to run with `--debug` option, but it doesn't help me a lot
Here is the logs
```bash
[DEBUG] 18:18:22 Starting child process -r /var/folders/m5/yrsjljh94jn01bjs1n66l3m40000gn/T/ts-node-dev-hook-12221350247358687.js -r ts-node/register -r tsconfig-paths/register (PATH)/node_modules/ts-node-dev/lib/wrap.js ./src/app.ts
[DEBUG] 18:18:22 (PATH)/src/app.ts added to watcher
[DEBUG] 18:18:24 (PATH)/src/app.ts compiled in 1394 ms
[DEBUG] 18:18:25 (PATH)/package.json added to watcher
[DEBUG] 18:18:25 (PATH)/src/config/constants.ts added to watcher
[DEBUG] 18:18:25 (PATH)/src/config/constants.ts compiled in 2 ms
[DEBUG] 18:18:25 (PATH)/src/config/passport.ts added to watcher
[DEBUG] 18:18:26 (PATH)/src/config/passport.ts compiled in 667 ms
[DEBUG] 18:18:26 Child error
[ERROR] 18:18:26 ⨯ Unable to compile TypeScript:
src/config/passport.ts:6:7 - error TS2451: Cannot redeclare block-scoped variable 'passport_1'.

6 const passport_1 = __importDefault(require("passport"));
        ~~~~~~~~~~

  src/app.ts:19:7
    19 const passport_1 = __importDefault(require("passport"));
             ~~~~~~~~~~
    'passport_1' was also declared here.

[DEBUG] 18:18:26 Disconnecting from child
(node:82365) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[DEBUG] 18:18:26 Child exited with code 0
```

You can go on [my repo](https://github.com/mlbonniec/bild), clone, and try to install what I've, but it's complex 😬

**Comment by snowinmars** [comment]
Yep, same issue to me.

I understand the reasons, but I don't know how to solve it properly.
