### ISSUE TITLE
Is it possible to exec npm script using ts-node-dev?

### ISSUE THREAD

**Issue by gerardolima** [wclr/ts-node-dev#253]
I like `ts-node-dev` and I'm trying to avoid using ts-node-dev and nodemon on the same project. Nodemon allows `nodemon ... --exec npm run test`. Is the same possible for `ts-node-dev`?

**Comment by wclr** [comment]
nodemon is more general tool, it can watch arbitrary files and execute an arbitrary command. ts-node-dev is for running a node process and restarting it on changes of files it required.

**Comment by ddehghan** [comment]
+1 for adding some way to run a script after each reload. We use that to copy over static files and I have seen people do that for running lint. 

I would live to use ts-node-dev but had to take it out because of this feature.

**Comment by gerardolima** [comment]
@ddehghan, I managed to use `ts-node-dev` to run eslint with the npm-script below (in my package.json). I works as expected, but I have to use the `node_modules/.bin/eslint`, instead of just `eslint`, and repeat all options that already exists in npm-script `lint`. I _feel_ that it should not take a lot of work to add npm context to `ts-node-dev`, but it's just not there 
```
"lint:w": "ts-node-dev --rs --debounce --transpile-only --respawn --inspect=7001 --watch './src/**/*.ts' -- node_modules/.bin/eslint './src/**/*.ts' --cache --cache-location out/.eslintcache",
```

**Comment by jwigley** [comment]
This would also be handy when using [tsoa ](https://github.com/lukeautry/tsoa), where we need to run a command to regenerate spec/routes after any changes.

Thanks @gerardolima, following your example I was able to get the following working using `concurrently` to run both server and regen command.
```json
  "dev": "concurrently \"npm run dev:spec\" \"npm run dev:server\"",
  "dev:spec": "ts-node-dev --respawn --transpile-only -- node_modules/tsoa/dist/cli.js spec-and-routes",
  "dev:server": "ts-node-dev --respawn --transpile-only ./src/server.ts"
```

**Comment by ErapidAPI** [comment]
@jwigley I am using tsoa as well but your solution isn't working for me.
when I make changes to my controllers, only the `dev:server` script runs but not the `dev:spec`.
can you share some more details on your setup?

**Comment by jwigley** [comment]
@ErapidAPI Try using the `--watch` option to explicitly set what you want to be watched.

eg. 
```json
    "dev:spec": "ts-node-dev --respawn --transpile-only --watch './src,tsoa.json' -- node_modules/tsoa/dist/cli.js spec-and-routes",
```

**Comment by dhatGuy** [comment]
@ErapidAPI Found a solution because it didn't for me too

**Comment by gerardolima** [comment]
hey, @wclr, may I assume this feature won't be considered for ts-node-dev?

**Comment by gerardolima** [comment]
closed due to no-response

**Comment by sephentos** [comment]
I apologize for reopening a closed issue, but I hope someone might have the time to take a look. I wish I could contribute, but unfortunately, I don't have the necessary expertise. Is there any chance this feature could be considered? It would be a major advantage over Nodemon for my use case. In fact, the only reason I still use Nodemon is because of this missing option.

**Comment by wclr** [comment]
Nodemon just watches and runs whatever. This package has another purpose: it runs and watches things that it runs.
