### ISSUE TITLE
Ignoring non-node_modules files

### ISSUE THREAD

**Issue by ekeuus** [wclr/ts-node-dev#261]
## Issue description

I am trying to ignore some locally linked node_modules in a Lerna monorepo, whose paths are resolved and thus don't contain node_modules.

The ignore config I am using: 
`{
	"ignore": [
		"node_modules",
		"/home/node/app/packages/db",
		"/home/node/app/packages/common"
	]
}
`

This row shows that the ignore is hardcoded:
https://github.com/wclr/ts-node-dev/blob/master/src/child-require-hook.ts#L112

I tried different options to ignore the linked libraries, but nothing worked. Am I misunderstranding something?

## Context

*OS version (is it docker or host?), ts-node-dev version*

*Did you try to run with [ts-node](https://github.com/TypeStrong/ts-node)*?

*Did you try to run with `--files` option enabled?*

*Did you try to run with `--debug` option enabled?*

*Do you have a repro example (git repo) with simple steps to reproduce your problem?*

**Comment by wclr** [comment]
> The ignore config I am using:

What  do you mean by "ignore config"?

**Comment by ekeuus** [comment]
The ignore watch. In the USA  section of the Readme. https://github.com/wclr/ts-node-dev

**Comment by ekeuus** [comment]
Maybe I misunderstood the fact that ts-node-dev uses a json file based config like node-dev.

**Comment by wclr** [comment]
Try to use cli option, I'm not maybe handling `node-dev.json` is not working the way it is supposed.

**Comment by ekeuus** [comment]
Thanks! Does the CLI option support regex? So, something like:

/(node_modules|xyz\/abc)/

**Comment by wclr** [comment]
--ignore should it will be passed to new RegExp, `--ignore-watch` - no, it is path start relative or absolute.
