### ISSUE TITLE
[BUG] jest-worker TypeError: Unexpected response from worker: undefined

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [wclr/ts-node-dev#264]
```sh
ts-node-dev --project tsconfig.server.json --respawn server/index.ts --watch server/*
```

server/indes.ts
```ts
import express from "express";
import next from "next";

const port = parseInt(process.env.PORT || "3000", 10);
const dev = process.env.NODE_ENV !== "production";
const app = next({ dev });
const handle = app.getRequestHandler();

// this call `jest-worker` and throw error
app.prepare();
```

```sh
TypeError: Unexpected response from worker: undefined
    at ChildProcessWorker._onMessage (C:\localhost\rollme\next\node_modules\jest-worker\build\workers\ChildProcessWorker.js:264:15)
    at ChildProcess.emit (events.js:327:22)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[ERROR] 15:34:37 TypeError: Unexpected response from worker: undefined
```

**Comment by applicazza** [comment]
In Next.js source code there is the [line](https://github.com/vercel/next.js/blob/218c6114c9f5ed5c6d65840037673c841f44536b/packages/next/next-server/server/config-utils.ts#L33) that causes tsnd to crash upon using jest workers launched with `{enableWorkerThreads: false}` options.

Theoretically until issue is resolved you could patch Next.js with [patch-package](https://www.npmjs.com/package/patch-package). However things like these are generally not recommended.

Related issue: #255

**Comment by blackavec** [comment]
i was struggling with this when i was running expressjs and nextjs 13 on ts-node-dev as well. `patch-package` that @applicazza mentioned didn't fix it either. 
after reading https://github.com/vercel/next.js/discussions/23070 figured that i have next.config.js at my root while i moved my next js to another directly `/frontend/ which also has the same file. after deleting it from root, it worked.
