### ISSUE TITLE
suggestion: update ts-node to version 10

### ISSUE THREAD

**Issue by benatshippabo** [wclr/ts-node-dev#267]
## Issue description
Currently we are using version 9 for `ts-node` https://github.com/wclr/ts-node-dev/blob/d2b7ec10b8cac7a630ea622473e4a9636c57b863/package.json#L53

however version 10 comes with [a few performance enhancements by enabling users to specify a third party TypeScript compiler like `swc`](https://typestrong.org/ts-node/docs/transpilers/#bundled-swc-integration) so it would be nice to have these options in `ts-node-dev` as well.

## Context

- https://github.com/TypeStrong/ts-node/issues/779
- https://github.com/TypeStrong/ts-node/releases/tag/v10.0.0

**Comment by dbousamra** [comment]
Any update on this? What needs to happen to do this? We would benefit a lot from being able to use other transpilers.

**Comment by benatshippabo** [comment]
@dbousamra There is also a duplicate ticket https://github.com/wclr/ts-node-dev/issues/286. I don't really see any breaking changes for `ts-node >= 10.0.0` so I think it should be an easy pull request. I'm not sure how the options for `ts-node-dev` are forwarded though (maybe @wclr could chime in), so we may need to add one in for `--transpiler`. 

Some alternatives I found for TypeScript development is vite and this plugin https://github.com/axe-me/vite-plugin-node

**Comment by benatshippabo** [comment]
The latest version now has this feature
