### ISSUE TITLE
Upgrade dateformat to address vulnerability in transitive dependency trim-newlines

### ISSUE THREAD

**Issue by karlhorky** [wclr/ts-node-dev#271]
## Issue description

Transitive dependency chain: `ts-node-dev@1.1.6 -> dateformat@~1.0.4-1.2.3 -> meow@^3.3.0 -> trim-newlines@^1.0.0`

Vulnerability: https://github.com/advisories/GHSA-7p7h-4mm5-852v

## Context

*OS version (is it docker or host?), ts-node-dev version*

macOS Big Sur 11.4, 1.1.6

*Did you try to run with [ts-node](https://github.com/TypeStrong/ts-node)*?

Not applicable

*Did you try to run with `--files` option enabled?*

Not applicable

*Did you try to run with `--debug` option enabled?*

Not applicable

*Do you have a repro example (git repo) with simple steps to reproduce your problem?*

Repro:

```bash
$ npm install ts-node-dev
...
$ npm audit
# npm audit report

trim-newlines  <3.0.1 || =4.0.0
Severity: high
Regular Expression Denial of Service - https://npmjs.com/advisories/1753
fix available via `npm audit fix`
node_modules/trim-newlines
  meow  3.4.0 - 5.0.0
  Depends on vulnerable versions of trim-newlines
  node_modules/meow

2 high severity vulnerabilities

To address all issues, run:
  npm audit fix
```

**Comment by Gabb-c** [comment]
Also, Dependabot is pointing this vulnerability too.

![image](https://user-images.githubusercontent.com/65926741/121529124-78af4680-c9d2-11eb-8646-131b700ce6d9.png)

**Comment by kamikazebr** [comment]
Yes, i see that CVE here too. I tried update the lock json manually and add in packaged the new version, but nothing. It's get replaced, so i think we need @wclr make that update, or better make the change suggested here https://github.com/wclr/ts-node-dev/pull/273#issuecomment-858491800

**Comment by jimmywarting** [comment]
- Fixed (removed dateformat)
- Made a release
- Can now close this issue

**Comment by kamikazebr** [comment]
Its Works! Tyvm!

**Comment by karlhorky** [comment]
Looks good! Closing.

```bash
$ npm install ts-node-dev
$ ...
$ npm audit
found 0 vulnerabilities
```
