### ISSUE TITLE
Node clusters require problem

### ISSUE THREAD

**Issue by xxSkyy** [wclr/ts-node-dev#277]
I've got fastify nodejs server, wanted to add clusters option to scale up application

File structure looks like
- app.ts
- src
- - routes
- - - index.ts
- - - route1.ts
- - - route2.ts

 index.ts file of routes are plugin for fastify that registers routes inside routes folder, so initializing it I've got normal registration of routes
```js
await app.register(require("./src/routes"))
```

and inside routes index.ts file
```js
export = (app, options, done) => {
  app.register(require("./route1"))
  app.register(require("./route2"))
}
```
everything works well normally but when I make it in clusters it doesnt work running ts-node-dev and just hangs  every process initializing routes, after compiling with tsc normal js code works well.
It's not really needed to use more than one process while development but I'd be good to fix it.
Also I can't really tell if its exact ts-node-dev problem or fastify problem with clustering (but I think its the first one as on build cluster all works perfect as on non cluster ts-node-dev).
Are there any fixes for now?

**Comment by filipeperdigaosousa** [comment]
Hi @xxSkyy, I'm facing exactly the same problem with a Koa server. 
Were you able to solve the problem?

**Comment by xxSkyy** [comment]
I guess @filipeperdigaosousa I can't help you, since then I've moved to graphql with `mercurius` and instead of clustering I'm using kubernetes pods. As I remember I wasn't able to fix it anyhow
