### ISSUE TITLE
ts-node-dev seems like it works without the "--respawn" flag

### ISSUE THREAD

**Issue by AndysonDK** [wclr/ts-node-dev#291]
This is more of a question than an issue. Does ts-node-dev still respawn processes without specifying the `--respawn` flag? In my local development it seems like it does

**Comment by wclr** [comment]
I believe no, you may try just to create a simple file with console output and run it, and then run it with respawn.

**Comment by AndysonDK** [comment]
aah yes you're right. I was confused because I was running an express server which just listens for events and keeps running
