### ISSUE TITLE
[ERROR] Must use import to load ES module

### ISSUE THREAD

**Issue by angelhdzmultimedia** [wclr/ts-node-dev#314]
## Issue description
![image](https://user-images.githubusercontent.com/10191085/171086526-48e4cca4-8b9a-4972-8537-e34a2d5efe98.png)

## Context
Totally new Node project with `typescript`, `@types/node`,  and `ts-node-dev` packages installed.
I only get this error when I set `type: "module"` in `package.json`.

### ts-node-dev: ^2.0.0

*OS version (is it docker or host?), ts-node-dev version*

*Did you try to run with [ts-node](https://github.com/TypeStrong/ts-node)*?

*Did you try to run with `--files` option enabled?*

*Did you try to run with `--debug` option enabled?*

*Do you have a repro example (git repo) with simple steps to reproduce your problem?*

**Comment by danlupascu** [comment]
I'm having the same problem

ts-node-dev version: 2.0.0
typescript version: 4.7.2

**Comment by angelhdzmultimedia** [comment]
Switched to babel with @babel/preset-typescript, and nodemon. Everything is working there. Can use imports without filenames, can use directories with implied index.ts, and can use mongoose. Will try other packages later to confirm that everything works now.

**Comment by angelhdzmultimedia** [comment]
Still having this issue with ts-node-dev. No matter what I try (type: "module" in package.json, module:"esnext" and module:"commonjs" in tsconfig.json, etc.)

Right now, my problem is with the package inquirer. It's ready for ESM in new version v9.0.0. But if I remove type: "module" from package.json, inquirer complains. Then I replaced the import with a dynamic import  await import('inquirer'), but then I get an error that can't use top level await with a commonjs module...

It's a paradox.

But with babel and nodemon, and babel typescript presets it works flawlessly.

I'm reaching the conclusion that ts-node-dev isn't ready for ESM so I will continue using babel and nodemon.

**Comment by halvors** [comment]
I have this exact same problem too, would it be possible to support this?

**Comment by dawosch** [comment]
Same problem.
I'm using `ts-node-dev` while i'm developing. And there the error occures.
When i build my project for production with bable it's woking.

**Comment by angelhdzmultimedia** [comment]
> Same problem. I'm using `ts-node-dev` while i'm developing. And there the error occures. When i build my project for production with bable it's woking.
Yeah, with babel works. 

You can try this config, I tested it with most ES2022 features (including Top Level Await)  and it works.

```json
{
  "type": "module",
  "name": "test_typescript_esm",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "dev": "nodemon -I --exec node --experimental-specifier-resolution=node  --loader ts-node/esm ./src/main.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "nodemon": "^2.0.19",
    "ts-node": "^10.9.1",
    "typescript": "^4.7.4"
  },
  "exports": "./dist/index.js",
  "devDependencies": {
    "@babel/core": "^7.18.2",
    "@babel/node": "^7.17.10",
    "@babel/plugin-proposal-decorators": "*",
    "@babel/preset-env": "^7.18.2",
    "@types/node": "^18.6.2"
  }
}

```

**Comment by ghost** [comment]
mark

**Comment by ChromeGG** [comment]
Same problem here. I tried with
```bash
ts-node-esm --experimental-specifier-resolution=node --transpile-only ./src/index
```
and it works BUT it'll not restart automatically if files will change

**Comment by angelhdzmultimedia** [comment]
### Update
Besides it working with Babel, I achieved to make it working with `nodemon `and `ts-node`.

Install nodemon and ts-node and of course typescript, set `type: "module"` in `package.json`,
and set `tsconfig.json` to:

```json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "moduleResolution": "Node",
    "module": "ESNext",
    "target": "ESNext"
  }
}
```

And then: `nodemon --exec node --loader ts-node/esm src/main.ts`

**Comment by zhoutengshen** [comment]
> I also encountered this problem. These contents may help you

> node version : v16.13.2

### package.json
```
{
  "devDependencies": {
    "@types/node": "^18.11.18",
    "nodemon": "^2.0.20",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.4"
  },
  "scripts": {
    "dev": "nodemon --exec ts-node index.ts --project ./tsconfig.json"
  },
  "type": "module"
}
```

###  tsconfig.json
```
{
  "extends": "ts-node/node16/tsconfig.json",
  "ts-node": {
    "transpileOnly": true,
    "files": true,
    // Tell ts-node CLI to install the --loader automatically, explained below
    "esm": true,
    "compilerOptions": {
      "module": "ESNext"
    }
  },
  "compilerOptions": {
    "module": "ESNext",
    "moduleResolution": "Node",
    "lib": [
      "DOM",
      "ES2015"
    ],
    "target": "ES2015"
  }
}
```

###

**Comment by angelhdzmultimedia** [comment]
> > I also encountered this problem. These contents may help you
> 
> > node version : v16.13.2
> 
> ### package.json
> ```
> {
>   "devDependencies": {
>     "@types/node": "^18.11.18",
>     "nodemon": "^2.0.20",
>     "ts-node": "^10.9.1",
>     "typescript": "^4.9.4"
>   },
>   "scripts": {
>     "dev": "nodemon --exec ts-node index.ts --project ./tsconfig.json"
>   },
>   "type": "module"
> }
> ```
> 
> ### tsconfig.json
> ```
> {
>   "extends": "ts-node/node16/tsconfig.json",
>   "ts-node": {
>     "transpileOnly": true,
>     "files": true,
>     // Tell ts-node CLI to install the --loader automatically, explained below
>     "esm": true,
>     "compilerOptions": {
>       "module": "ESNext"
>     }
>   },
>   "compilerOptions": {
>     "module": "ESNext",
>     "moduleResolution": "Node",
>     "lib": [
>       "DOM",
>       "ES2015"
>     ],
>     "target": "ES2015"
>   }
> }
> ```

Thank you!

**Comment by oxilor** [comment]
According to the [typescript documentation](https://www.typescriptlang.org/tsconfig#moduleResolution) the `moduleResolution` must be:
- `node` for Node.js’ CommonJS implementation
- `nodenext` for Node.js’ ECMAScript Module Support from TypeScript 4.7 onwards.

So the `moduleResolution` must be `nodenext` for ESM. I created the [repository](https://github.com/oxilor/nodemon-ts-esm) with minimum configuration for restarting the node app when the file changes. It uses `nodemon`, because the `ts-node-env` doesn't seem to support ESM yet.

**Comment by angelhdzmultimedia** [comment]
I'm using tsx now. No issues so far.

But thanks for the update. I'm gonna try ts-node-dev again with module resolution set to nodenext.

Is the ts-node set to esm mandatory?

**Comment by oxilor** [comment]
@angelhdzmultimedia Wow, `tsx` looks even better. I'll try it. Thanks.

> Is the ts-node set to esm mandatory?

Unfortunately, I don't quite understand your question. To make ts-node compatible with ESM, we should use the appropriate loader in one of the [following ways](https://github.com/TypeStrong/ts-node#esm), but `ts-node-dev` (v2.0.0) still throws an error if ESM is used (Must use import to load ES Module).

P.S. `tsx` [does not support](https://github.com/esbuild-kit/tsx#does-it-do-type-checking) type checking. We can, of course, run the TS compiler at first `tsc --noEmit && tsx watch src/index.ts`, but in this case, if we violated some types during watch mode, `tsx` doesn't show any errors. This seems to be the main reason why `tsx` is faster than, for example, `ts-node`. IMO it's inconvenient, because we don't immediately know about mistakes in types.

We are looking forward to ESM support in `ts-node-dev`. In the meantime, we can use `nodemon` + `ts-node` if we need to check types in watch mode, or `tsx` if not.

**Comment by angelhdzmultimedia** [comment]
> @angelhdzmultimedia Wow, `tsx` looks even better. I'll try it. Thanks.
> 
> > Is the ts-node set to esm mandatory?
> 
> Unfortunately, I don't quite understand your question. To make ts-node compatible with ESM, we should use the appropriate loader in one of the [following ways](https://github.com/TypeStrong/ts-node#esm), but `ts-node-dev` (v2.0.0) still throws an error if ESM is used (Must use import to load ES Module).
> 
> P.S. `tsx` [does not support](https://github.com/esbuild-kit/tsx#does-it-do-type-checking) type checking. We can, of course, run the TS compiler at first `tsc --noEmit && tsx watch src/index.ts`, but in this case, if we violated some types during watch mode, `tsx` doesn't show any errors. This seems to be the main reason why `tsx` is faster than, for example, `ts-node`. IMO it's inconvenient, because we don't immediately know about mistakes in types.
> 
> We are looking forward to ESM support in `ts-node-dev`. In the meantime, we can use `nodemon` + `ts-node` if we need to check types in watch mode, or `tsx` if not.

My question is, is it mandatory to add this:

![image](https://user-images.githubusercontent.com/10191085/221391989-e3e2db9a-b032-4295-a5ef-916b3d9e1fa5.png)


And yes, you're right about tsx.

I've been also using `nodemon --exec "node --loader ts-node/esm src/main.ts"` or just `node --loader ts-node/esm` and it works great.

I'm exited to see ts-node-dev being improved.

**Comment by oxilor** [comment]
@angelhdzmultimedia,

> My question is, is it mandatory to add this

We should somehow tell `ts-node` to use the loader that supports ESM. This can be done in one of the following ways:

### 1. Specify in `tsconfig.json` that the `ts-node` uses ESM loader
```json
{
  "ts-node": {
    "esm": true
  }
}
```

In this case, you don't need to specify additional arguments in nodemon command:
```sh
nodemon src/index.ts
```

### 2. Specify the `ts-node` command with ESM in nodemon:
```sh
nodemon --exec ts-node-esm src/index.ts
```
or
```sh
nodemon --exec 'ts-node --esm' src/index.ts
```

In this case, you don't need to change the `tsconfig.json` file.

### 3. Set `ts-node` with ESM as the node loader
```sh
NODE_OPTIONS='--loader ts-node/esm' nodemon src/index.ts
```
or
```sh
nodemon --exec 'node --loader ts-node/esm' src/index.ts
```

I prefer the first case (set `ts-node.esm` to true in tsconfig), because it looks cleaner.

**Comment by angelhdzmultimedia** [comment]
I appreciate your kind responses A LOT!!! They have been on fire🔥, on point👌!

Sorry to bother you with one last question... ❔

Difference between `ts-node/esm` and `ts-node-esm` flags? Both allowed or is one of them deprecated? 

Wishing you health, peace, and success!

**Comment by oxilor** [comment]
Seems that `ts-node-esm` and `ts-node --esm` [are aliases of commands](https://github.com/TypeStrong/ts-node#esm). `ts-node/esm` is the [node loader](https://github.com/TypeStrong/ts-node#node-flags-and-other-tools). 

I don't see any of them being deprecated at the moment. So you can use any of these methods that you like best.

**Comment by ThallesP** [comment]
Got one-liner working with nodemon:
```bash
npx nodemon -e ts,json --exec 'node --experimental-specifier-resolution=node --loader ts-node/esm' <path>.js
```

**Comment by RangerCoder99** [comment]
> ```shell
> npx nodemon -e ts,json --exec 'node --experimental-specifier-resolution=node --loader ts-node/esm' <path>.js
> ```

not working on windows :(

**Comment by angelhdzmultimedia** [comment]
> 

![image](https://user-images.githubusercontent.com/10191085/234133493-793677c3-0843-4195-9bb7-b935e00fae63.png)

I don't know what you're trying to achieve, but I got it working with:

`npx nodemon -e ts,json --exec node --experimental-specifier-resolution=node --loader ts-node/esm main.ts`

Where `main.ts` is my main file in the root of my project.

![image](https://user-images.githubusercontent.com/10191085/234134620-6b8da3c0-d465-4357-b580-955b70d38c03.png)

**Comment by RicFer01** [comment]
> @angelhdzmultimedia,
> 
> > My question is, is it mandatory to add this
> 
> We should somehow tell `ts-node` to use the loader that supports ESM. This can be done in one of the following ways:
> 
> ### 1. Specify in `tsconfig.json` that the `ts-node` uses ESM loader
> ```json
> {
>   "ts-node": {
>     "esm": true
>   }
> }
> ```
> 
> In this case, you don't need to specify additional arguments in nodemon command:
> 
> ```shell
> nodemon src/index.ts
> ```
> 
> ### 2. Specify the `ts-node` command with ESM in nodemon:
> ```shell
> nodemon --exec ts-node-esm src/index.ts
> ```
> 
> or
> 
> ```shell
> nodemon --exec 'ts-node --esm' src/index.ts
> ```
> 
> In this case, you don't need to change the `tsconfig.json` file.
> 
> ### 3. Set `ts-node` with ESM as the node loader
> ```shell
> NODE_OPTIONS='--loader ts-node/esm' nodemon src/index.ts
> ```
> 
> or
> 
> ```shell
> nodemon --exec 'node --loader ts-node/esm' src/index.ts
> ```
> 
> I prefer the first case (set `ts-node.esm` to true in tsconfig), because it looks cleaner.

Thanks to your suggestions I got it working! There is one thing I didn't get, I'm using TS, why do I need to import file adding the extension and this extension has be in `.js`?
```
import app from './api.js'
```

**Comment by cincarnato** [comment]
@RicFer01  Your last question have the answer here: https://www.typescriptlang.org/docs/handbook/esm-node.html
 
![image](https://github.com/wclr/ts-node-dev/assets/7002030/ee37d359-c8b2-4d46-a9c3-f8e741d6d529)

**Comment by RicFer01** [comment]
> @RicFer01 Your last question have the answer here: [typescriptlang.org/docs/handbook/esm-node.html](https://www.typescriptlang.org/docs/handbook/esm-node.html)
> 
> ![image](https://user-images.githubusercontent.com/7002030/239708759-ee37d359-c8b2-4d46-a9c3-f8e741d6d529.png)

Thank you!

**Comment by ivannalon** [comment]
> I'm using tsx now. No issues so far.
> 
> But thanks for the update. I'm gonna try ts-node-dev again with module resolution set to nodenext.
> 
> Is the ts-node set to esm mandatory?

Are you using it in conjunction with docker? My tsx doesn't work watch mode in the container.

**Comment by ivannalon** [comment]
> I'm using tsx now. No issues so far.
> 
> But thanks for the update. I'm gonna try ts-node-dev again with module resolution set to nodenext.
> 
> Is the ts-node set to esm mandatory?

Are you using it in conjunction with docker? My tsx doesn't work watch mode in the container.

**Comment by rtlayzell** [comment]
Repo is looking stale, fair to say this isn't getting fixed any time soon?

**Comment by jaclas** [comment]
and still nothing?

**Comment by itxtoledo** [comment]
same error here

**Comment by Marcelofj** [comment]
I solved my problem by simply removing "type" : "module" from package.json

**Comment by ThallesP** [comment]
if anyone want an alternative, i use [tsx](https://www.npmjs.com/package/tsx) for about sometime and i love it, simple to use and maintained.

**Comment by rolanday** [comment]
> I solved my problem by simply removing "type" : "module" from package.json

Sorry, but this is not a solution.

**Comment by rolanday** [comment]
+1 for `tsx` -- it doesn't perform type checking though, so just keep that in mind. I just add  `"check": "tsc --noEmit"` to my package.json script and spot check occasionally (or a full build), and good linter setup goes a long way.

**Comment by Marcelofj** [comment]
> > I solved my problem by simply removing "type" : "module" from package.json
> 
> Sorry, but this is not a solution.

For me it is. Works fine.

My package.json:



`{
  "name": "general",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "dev": "ts-node-dev --respawn --transpile-only src/app.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "ts-node-dev": "^2.0.0",
    "typescript": "^5.1.6"
  }
}`

**Comment by devgrunge** [comment]
> > I also encountered this problem. These contents may help you
> 
> > node version : v16.13.2
> 
> ### package.json
> ```
> {
>   "devDependencies": {
>     "@types/node": "^18.11.18",
>     "nodemon": "^2.0.20",
>     "ts-node": "^10.9.1",
>     "typescript": "^4.9.4"
>   },
>   "scripts": {
>     "dev": "nodemon --exec ts-node index.ts --project ./tsconfig.json"
>   },
>   "type": "module"
> }
> ```
> 
> ### tsconfig.json
> ```
> {
>   "extends": "ts-node/node16/tsconfig.json",
>   "ts-node": {
>     "transpileOnly": true,
>     "files": true,
>     // Tell ts-node CLI to install the --loader automatically, explained below
>     "esm": true,
>     "compilerOptions": {
>       "module": "ESNext"
>     }
>   },
>   "compilerOptions": {
>     "module": "ESNext",
>     "moduleResolution": "Node",
>     "lib": [
>       "DOM",
>       "ES2015"
>     ],
>     "target": "ES2015"
>   }
> }
> ```

It worked well for me!
using at my package.json:

`  "dev": "nodemon --exec ts-node ./src/index.ts --project ./tsconfig.json"`

**Comment by t-benze** [comment]
> I'm using tsx now. No issues so far.
> 
> But thanks for the update. I'm gonna try ts-node-dev again with module resolution set to nodenext.
> 
> Is the ts-node set to esm mandatory?

This is good! Thanks

**Comment by VladyslavMalyshenko** [comment]
> "dev": "nodemon --exec ts-node index.ts --project ./tsconfig.json"

This one actually helped me. Thank you so much.

**Comment by mblackrittr** [comment]
> > > I solved my problem by simply removing "type" : "module" from package.json
> > 
> > 
> > Sorry, but this is not a solution.
> 
> For me it is. Works fine.

Löl, no, it doesn't! 😹💦

Well, yeah, yeah, always the same everywhere - it "works" for them... löl
... exactly until they'll've to **resolve** it - just because `"type": "module"` is ***NOT*** something optional one can set as he wishes - gruesome! 🙀

**Comment by mblackrittr** [comment]
> if anyone want an alternative, i use [tsx](https://www.npmjs.com/package/tsx) for about sometime and i love it, simple to use and maintained.

Thanks @ThallesP, works as great as you say - ***WoooF!*** 😹💦

**Comment by life-is-dlc** [comment]
It is built on top of ts-node, and ts-node is a...please search on stackoverflow for solutions like`--esm`, remove `{ "type": "module" }`...you will end up being recommended with `tsx` any way. lol

**Comment by teadrinker2015** [comment]
It is built on top of ts-node, and ts-node is a ... please search on stackoverflow for solutions like `--esm`, remove `{ "type": "module" }` ... you will end up being recommended with `tsx` any way.

**Comment by angelhdzmultimedia** [comment]
I'm lately using `node --watch ts-node/esm src/main.ts`

And in `tsconfig.json`:
{
 "ts-node": {
    "experimentalSpecifierResolution": "node",
    "transpileOnly": true,
    "esm": true,
  }
}
 
And works... good...
 I dream of a day where there's only 1 configuration and working with TypeScript + Node is a pleasure...
 Waiting for Bun Windows 👀

**Comment by mblackrittr** [comment]
> I'm lately using `node --watch ts-node/esm src/main.ts`

I wonder what issues await the brave on that path (with latest Node, etc.), but would you share with us - why it's not `TSX` anymore for you?

Just using it a day now, but works great so far, even with latest `Node` `21.7.1`.

And beside tons of features, it can also watch, same as `TS-Node`:
```sh
> tsx watch ./file.ts
```

**Comment by IzaelGomes** [comment]
i solved this problem removing "type": "module" from my package.json and keeping just "module": "CommonJS" on my tsconfig.json. it works fine.

**Comment by angelhdzmultimedia** [comment]
Bun for Windows is out guys! 🔥👀✌️🤣

Bun, tsx, unjs/jiti. Solid options now.

Closing this.

**Comment by mblackrittr** [comment]
> i solved this problem removing "type": "module" from my package.json and keeping just "module": "CommonJS" on my tsconfig.json. it works fine.

Yeah, yeah, "solved" and "works fine" (always were the words of the ignorant) - see you again later in the day when you figure out it'll blow on all these ***"EVIL"*** `ESM only packages` or any other valid reason for `ESM`, e.g. publishing a package for others to use - then no `ESM`?! 😹💦

**Comment by iVergos** [comment]
I solved this problem by running npm update ts-node-dev

**Comment by stolbov-stanislav** [comment]
Hi guys!

I just solved the same problem by generating tsconfig (`tsc --init` or `npx tsc --init`).

Here is my package.json:
`{
  ...
  "main": "index.js",
  "scripts": {
    "dev": "ts-node-dev --pretty --respawn ./src/app.ts"
  },
  ...
  "devDependencies": {
    "@types/cors": "^2.8.17",
    "@types/dotenv": "^8.2.3",
    "@types/express": "^5.0.0",
    "@types/helmet": "^4.0.0",
    "@types/http-status-codes": "^1.2.0",
    "@types/uuid": "^10.0.0",
    "ts-node-dev": "^2.0.0",
    "typescript": "^5.7.3"
  },
  "dependencies": {
    "cors": "^2.8.5",
    "dotenv": "^16.4.7",
    "express": "^4.21.2",
    "helmet": "^8.0.0",
    "http-status-codes": "^2.3.0",
    "uuid": "^11.0.4"
  }
}`

Here is my tsconfig.json:
`{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs", 
    "esModuleInterop": true, 
    "forceConsistentCasingInFileNames": true, 
    "strict": true,
    "skipLibCheck": true 
  }
}`

I'll be glad if this helps someone 🙂

**Comment by TuralAsgar** [comment]
Just use `tsx` instead of `ts-node-dev`.
It is very easy and has 0 configuration.

**Comment by EziosWJ** [comment]
> Just use `tsx` instead of `ts-node-dev`. It is very easy and has 0 configuration.

everything became good

**Comment by iVergos** [comment]
> Just use `tsx` instead of `ts-node-dev`.
> It is very easy and has 0 configuration.

Yep, that's how I also got past this. Sorry I didn't post it earlier..
