### ISSUE TITLE
ts-node-dev fails to restarts after change

### ISSUE THREAD

**Issue by kaykhan** [wclr/ts-node-dev#318]
## Issue description

When i make a change ts-node-dev never restarts

```
Server Running On: 0.0.0.0:3001
[INFO] 10:28:57 Restarting: /home/kay/checkpoint/admin-dashboard/backend/src/api/brands/brand.service.ts has been modified
[DEBUG] 10:28:57 /home/kay/checkpoint/admin-dashboard/backend/src/api/brands/brand.service.ts compiled in 48 ms
[DEBUG] 10:28:57 Removing all watchers from files
[DEBUG] 10:28:57 Child is still running, restart upon exit
[DEBUG] 10:28:57 Disconnecting from child
[DEBUG] 10:28:57 Sending SIGTERM kill to child pid 23479
```

## Context

*OS version (is it docker or host?), ts-node-dev version* 2.0.0

*Did you try to run with [ts-node](https://github.com/TypeStrong/ts-node)*? yes

*Did you try to run with `--files` option enabled?* no

*Did you try to run with `--debug` option enabled?* yes

*Do you have a repro example (git repo) with simple steps to reproduce your problem?* no

**Comment by everhardt** [comment]
Are you exiting your process on SIGTERM? Something like
```
process.on('SIGTERM', () => {
  console.log('SIGTERM received, exiting');
  process.exit(0);
});
```

**Comment by mkosir** [comment]
ts-node-dev restart also stopped working for me, I added `--exit-child` flag and it restarts normal after making a change.

I added this flag because of the @everhardt answer, could you elaborate why is this necessary 🤔

**Comment by everhardt** [comment]
In my case I use the SIGTERM listener to gracefully shutdown in production as well, so I never tried `--exit-child`, but [it looks like it's the same](https://github.com/wclr/ts-node-dev/blob/32bdc92458a59f66bcbd36e87de2a793f529a825/src/child-require-hook.ts#L152:L157).
