### ISSUE TITLE
Upgrade ts-node to v10.9.2

### ISSUE THREAD

**Issue by unematiii** [wclr/ts-node-dev#342]
## Issue description

Bug/issue in ts-node v10.9.1 prevents us using this tool with Typescript 5.3. Fixed in v10.9.2. 

## Context

*macOS Sonoma, ts-node-dev version 2.0.0

*Did you try to run with [ts-node](https://github.com/TypeStrong/ts-node)? Yes

See https://github.com/TypeStrong/ts-node/issues/2098#event-11194208861

**Comment by flex-junwoo** [comment]
any update here?

**Comment by wclr** [comment]
Shouldn't  "ts-node": "^10.4.0", https://github.com/wclr/ts-node-dev/blob/master/package.json#L53 install the latest version of 10.x.x?

**Comment by flex-junwoo** [comment]
To use TypeScript 5.3.x, need to have ts-node version 10.9.2.
So, this is an issue requesting an upgrade of the version.

**Comment by wclr** [comment]
If your package manager installed the earlier version of ts-node (for ts-node-dev) just remove and re-add `ts-node-dev`, it should install with it the latest available ts-node 10.x.x.
