### ISSUE TITLE
How to use ts-node-dev in js file like nodemon

### ISSUE THREAD

**Issue by kelefun** [wclr/ts-node-dev#350]
I want use ts-node-dev in script.js ,but don't know how .
How to using  ts-node-dev like nodemon below
```javascript
var nodemon = require('nodemon');

nodemon({ script: 'app.js' }).on('start', function () {
  console.log('nodemon started');
}).on('crash', function () {
  console.log('script crashed for some reason');
});

// force a restart
nodemon.emit('restart');

// force a quit
nodemon.emit('quit');
```

**Comment by wclr** [comment]
It is not intended to work as nodemon, you probably can use nodemon to run TS.

**Comment by kelefun** [comment]
> It is not intended to work as nodemon, you probably can use nodemon to run TS.

nodemon not work well with typescript(maybe it's my problem). 
For now i use [tsx](https://www.npmjs.com/package/tsx) works well.
Any way, thanks for your reply.
Have good day
